# Generated by Django 6.0 on 2026-06-08 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, help_text='Прежний числовой id из content.ts', null=True)),
                ('name', models.CharField(max_length=120)),
                ('subtitle', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Разработка', 'Разработка'), ('SMM', 'SMM')], max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('accent', models.CharField(help_text='HEX, напр. #14B8A6', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате HEX, напр. #14B8A6', regex='^#[0-9A-Fa-f]{6}$')])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('url', models.URLField(blank=True, help_text='Внешняя ссылка кейса; пусто → «Кейс скоро»', null=True)),
                ('initials', models.CharField(blank=True, help_text='Ручной fallback («IC»); пусто → берётся из name', max_length=4, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Стабильный id: designer, smm, frontend …', max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('tagline', models.CharField(max_length=255)),
                ('type', models.CharField(help_text='Напр. «Полная занятость · Душанбе» (свободный текст)', max_length=120)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('icon', models.CharField(choices=[('Palette', 'Palette'), ('Megaphone', 'Megaphone'), ('Handshake', 'Handshake'), ('Code2', 'Code2'), ('Target', 'Target'), ('Clapperboard', 'Clapperboard')], max_length=20)),
                ('accent', models.CharField(choices=[('brand-500', 'brand-500'), ('brand-600', 'brand-600'), ('brand-700', 'brand-700')], max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
