# Generated by Django 6.0 on 2026-06-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lead', 'Заявка с формы'), ('application', 'Отклик на вакансию')], default='lead', max_length=20)),
                ('role', models.CharField(blank=True, help_text='slug вакансии, если kind=application', max_length=60, null=True)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(help_text='email или @telegram', max_length=60)),
                ('phone', models.CharField(max_length=20)),
                ('selected', models.JSONField(blank=True, default=list)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('is_sent_to_telegram', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
