# Generated by Django 6.0 on 2026-06-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Необязательное сообщение (отклик на вакансию)'),
        ),
    ]
