# Generated by Django 6.0 on 2026-06-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='experience',
            field=models.CharField(blank=True, choices=[('без опыта', 'без опыта'), ('до 1 года', 'до 1 года'), ('1–3 года', '1–3 года'), ('3–5 лет', '3–5 лет'), ('5+ лет', '5+ лет')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
