# Generated by Django 6.0 on 2026-06-10 10:14

import apps.leads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_age_lead_experience_lead_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=apps.leads.models.resume_upload_path),
        ),
    ]
