# Generated by Django 6.0.6 on 2026-06-10 11:04

import apps.leads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=apps.leads.models.select_resume_storage, upload_to=apps.leads.models.resume_upload_path),
        ),
    ]
